### ISSUE TITLE
Add a new command type: append

### ISSUE THREAD

**Issue by stefhol** [iBicha/playlet#129]
My use case is the following I use a Apple Shortcut to send a post request to the service. It works really good I surf youtube.com on my phone and click under the share menu my shortcut "Play on Playlet". Problem is I just wanna queue more videos. For that I only need an API Endpoint with a play queue and I would be very happy.

**Comment by iBicha** [comment]
That's a great idea, thanks for the feature request!

First, I was looking for a way to get a "casting" mechanism from either the official Youtube app, or 3rd party apps like [NewPipe](https://newpipe.net/). My first reflex was a native app that the Youtube app could share to. 
I have not considered something like Apple Shortcut.

For the queue endpoint, I was planning on it for sure. It should come with playlist support as these two are related.

Finally, I generally think that rest APIs should be stable, but I thought of playlet apis as "internal" since I always assumed it doesn't have callers other than the web app. But now you've given me something to think about as the apis go through some changes in the near future, and I should avoid breaking changes as much as possible

**Comment by stefhol** [comment]
I don't mind breaking changes 😀. In the meantime would it be possible to merge a pull request on the current main with a simple queue system? Or will your rewrite soon be finsihed? As you said it is in an internal API with probably one user, me

**Comment by iBicha** [comment]
> I don't mind breaking changes 😀. In the meantime would it be possible to merge a pull request on the current main with a simple queue system? Or will your rewrite soon be finsihed? As you said it is in an internal API with probably one user, me

The rewrite is still happening, it makes sense to land this in the main branch for now. If you want to take a stab at it, please do create a pull request!

**Comment by iBicha** [comment]
The concept of a queue has been introduced. While it doesn't have proper UI yet, but you can add to the queue from the web app. Also, the API is described [here](https://github.com/iBicha/playlet/blob/50858c150fa894e54aef2a8c1a5582746a559957/docs/playlet-web-api.yml#L163)

Playlists are also supported now, which will allow you to play videos one after the other
