### ISSUE TITLE
Availability in Europe

### ISSUE THREAD

**Issue by renmarq** [iBicha/playlet#154]
Hi,

I'm in Europe and it's not possible to install the app from the official store. Would you be able to make it available is all region? As an alternative I tried to install the git version locally but it only run while my computer is running (as per documentation) which is not practical. If not possible maybe there is a way to deploy locally but with remote server configuration?

Thank you.

**Comment by iBicha** [comment]
Thank you so much for pointing this out. I was under the impression that I made Playlet available everywhere.

First, I'll double check the publish settings and make sure to make it available to all supported countries.

Second, you can "`deploy locally but with remote server configuration`". In VS Code, instead of launching `Playlet (prod)` instead of `Playlet (dev)`. This should point it to the latest release by default instead of a dev server.

<img width="291" alt="Screen Shot 2023-09-29 at 3 05 37 PM" src="https://github.com/iBicha/playlet/assets/17722782/7978ef65-00ab-47c3-9cd5-6a940ea35a6b">

Finally, in the `App Info` tab (on the TV or the web app) verify the value of `Playlet Library URL`. It should say `https://github.com/iBicha/playlet/releases/latest/download/playlet-lib.zip`.

**Comment by iBicha** [comment]
Can you share which country you're using Playlet from? I've made Playlet available to all possible options, so i'm not sure how to investigate this issue.

**Comment by renmarq** [comment]
Sure. I'm in Belgium.

Thanks for the tip on deploying production version, I just did and it works!

**Comment by iBicha** [comment]
I have all available countries selected (Belgium is not listed) but the option "Rest of World" so I thought this actually makes the app available everywhere. But perhaps not based on this https://community.roku.com/t5/Roku-setup/Which-International-Countries-Can-Use/td-p/788254

This is the list of countries available to me, and they are all enabled
```
United States
Argentina
Australia
Brazil
Canada
Chile
Colombia
Costa Rica
El Salvador
France
Germany
Guatemala
Honduras
Ireland
Mexico
Nicaragua
Panama
Peru
Rest of World
United Kingdom
```

I think that's the best we can do for now unfortunately. If anyone can't use the app from the store, they can rely on using `Playlet (prod)` (but that means using the `dev`, and you can only have one installed at a time)

**Comment by renmarq** [comment]
Yes it's very likely, I had to import my Roku from another country in the first place. I think I then had to tweak my account through VPN etc. to be able to install some channels in the past. For the moment the dev install will work for me. Thank you very much!

**Comment by iBicha** [comment]
Added a guide to install Playlet as a sideloaded dev app https://github.com/iBicha/playlet/discussions/371
