### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by PDXUser** [iBicha/playlet#22]
App is not movable.  We would love to be able to move it next to the Youtube App instead of it being on the bottom of the channel list.  

The ability to clear/remove search history.  Not that it's a bad thing to have but having the option to do so would be fantastic!

**Comment by iBicha** [comment]
Thanks for the suggestions @PDXUser !

> App is not movable. We would love to be able to move it next to the Youtube App instead of it being on the bottom of the channel list.

Unfortunately this is a limitation of sideloaded apps. When an app is installed from source and not from the store, there's a few limitations
- You can only install one sideloaded app at a time (they all have the same identifier, "dev")
- The "dev" app is always at the end of the list

With that in mind, the only way to make it movable is to publish to the Roku channel store. So far I did not plan to publish Playlet to the channel store store because I'm 99% they will reject it (Obviously they will side with Google on this one).
But I'm not sure, maybe it's worth giving a try


> The ability to clear/remove search history. Not that it's a bad thing to have but having the option to do so would be fantastic!

This is a must have feature (we should have search history and watch history, and the ability to clear both) I added this to the roadmap for v0.6.0

**Comment by iBicha** [comment]
I have addressed the search history in #26 so it's now possible to do that.
It can be improved UX wise.
As for publishing to the official Roku store, I don't think we can do that, without a plan in place on how to prevent it from getting rejected. 
This should cover this issue. If there's any other issue, please feel free to create a new one!
