### ISSUE TITLE
Error playing tons of videos

### ISSUE THREAD

**Issue by TheBossMan3** [iBicha/playlet#233]
![image](https://github.com/iBicha/playlet/assets/137230614/abcf9e66-fbd7-4247-9063-5d80d5c64b51)
It can’t seem to play All I Want For Christmas Is You or Christmas Tree Farm at all

**Comment by iBicha** [comment]
Thanks for sharing the error - can you share your setup please?
You get that from `http://ROKU_IP:8888/api/state`

**Comment by TheBossMan3** [comment]
Do you want the full document or just а part of it

**Comment by iBicha** [comment]
You can share the whole thing and remove any information you're not comfortable with sharing. Or you can share using email (You can do that through the web app in the info tab)

I already suspect something, but can't validate without seeing the settings: When I play `All I Want For Christmas Is You`
- Using my instance hosted on my home network: the video plays fine immediately (quality = DASH)
- Using public instance `https://invidious.fdn.fr`: it gets blocked on the first try (DASH), but the second try succeeds (DASH+proxy).

This makes sense, since I'm querying the video information from France, and then trying to play the video from Canada. Youtube detects this kind of stuff on certain videos and geoblocks things. This doesn't happen on my own instance, since my TV and my server are sharing the same public IP address.

It all depends on the instance used and your Playlet settings. In addition, some instances have proxying disabled (because it is bandwidth intensive $$$).

**Comment by TheBossMan3** [comment]
{"app":{"app_git_commit_hash":"826228e939deb69fb0957c53fbde2b7ee159b24a","app_version":"0.17.2","id":"693751","lib_git_commit_hash":"132e3ec3e3485db0d00c89c77fd395ea3cca541a","lib_url":"https://github.com/iBicha/playlet/releases/download/canary/playlet-lib.zip","lib_url_type":"custom","lib_version":"0.17.3","lib_version_latest":"0.17.3"},"device":{"display_aspect_ratio":"16x9","display_mode":"720p","display_size":{"h":720,"w":1280},"display_type":"HDTV","friendly_name":"Family Rm 55\" TCL Roku TV Ser 6","graphics_platform":"opengl","internet_status":true,"model":"J000X","model_details":{"Manufacturer":"TCL","ModelNumber":"J101X","ScreenSize":55,"VendorName":"TCL","VendorUSBName":"Trinidad_TCL_TCL_X021"},"model_display_name":"55R655","model_type":"TV","os_version":{"build":"4176","major":"12","minor":"5","revision":"0"},"ui_resolution":{"height":1080,"name":"FHD","width":1920},"user_country_code":"US","video_mode":"2160p60"},"invidious":{"auth_url":"http://invidious.fdn.fr/authorize_token?scopes=GET%3Afeed%2CGET%3Aplaylists*%2CPOST%3Atokens%2F*%2C%3Ahistory*%2C%3Asubscriptions*&callback_url=http%3A%2F%2F192.168.50.148%3A8888%2Finvidious%2Ftoken_callback%3Fref%3Dhttps%3A%2F%2Finvidious.fdn.fr&expire=1766200714","current_instance":"https://invidious.fdn.fr","logged_in":true,"logged_in_instance":"https://invidious.fdn.fr","logged_in_username":"anonymous-3127"},"preferences":{"__version":1,"invidious.instance":"","invidious.proxy_videos":"never","misc.queue_notifications":true,"playback.autoplay":true,"playback.preferred_quality":"auto","search_history.enabled":true,"sponsorblock.enabled":true,"sponsorblock.show_notifications":true}}

**Comment by iBicha** [comment]
Ok I think this case is clear. You're in the US and using `http://invidious.fdn.fr`, which is in France.
Youtube will detect that something is off. For some videos and using this particular server, some videos will only work through proxying. You setting `Proxy videos` is set to `Never`. This means if the video is blocked without a proxy, it will not try a proxy.

You can try to change the Invidious instance you're using, or set the `Proxy videos` to `Only if needed`. This way it will try to load the video directly from Youtube, and if it gets blocked, it will try again by proxy.

I hope this helps.

**Comment by TheBossMan3** [comment]
Thank you! I forgot I even set that

**Comment by iBicha** [comment]
Glad things are working! Closing the issue
