### ISSUE TITLE
Feature request - be able to provide own invidious URL (for self-hosted)

### ISSUE THREAD

**Issue by vadimzharov** [iBicha/playlet#24]
Thank you for this great app! Installed it on my Roku TV and it works perfectly.
I'm trying to self-host as much as I can, so I also have self-hosted invidious instance.

I think it would be great if users be able to specify (force app to use) their own invidious instance URL - so the app can work in self-hosted environment.
I'm not a developer, so I cannot make proper code changes, but I tested the app with my self-hosted invidious instance by changing 
`const DEFAULT_INSTANCE = "https://<my invidious instance URL>" `
and commenting all code in function `GetCurrentInstances` in InvidiousSettings.bs file.
With this change Playlet plays videos from my self-hosted instance - so in general it is possible.

So would be great to have this feature in roadmap.

**Comment by iBicha** [comment]
Hey @vadimzharov, thanks for the request.
It's possible to change the Invidious instance without modifying the code!

#### First, go to the settings screen in Playet:
<img src="https://raw.githubusercontent.com/iBicha/playlet/7fd466fb252911ac4e0253811c79a02ee6f25cda/screenshot3.jpg" alt="Screenshot of Playlet" width="350"/>

The screen will show you a web address that you can open from a mobile or desktop browser (scan with qr code for quick access) 


The screen will look like very barebone html file. You should see a list of Invidious Instances in a table.
Playlet will show the first one in BOLD, which also indicates the one being used.
<img src="https://user-images.githubusercontent.com/17722782/205520912-61d19436-0fb3-4d3d-a763-841b786e0e98.png" alt="Screenshot_20221204-175932" width="350"/>

#### Next, click on the "Remove" button on all the instances, then enter your instance, click "Add" (1), then click "Update Instances" (2)
<img src="https://user-images.githubusercontent.com/17722782/205521132-9ad6a462-7290-45b4-9f72-cc244bbf8fc7.png" alt="Screenshot_20221204-180028" width="350"/>

And that's about it. All requests will now be done through you instance you provided. You can restart the app to also reflect changes to the home page

A couple of notes:

- The flow still needs to UX revamping. It needs to be easier and more intuitive to change settings, like the Invidious instance. Still trying to find to time to design a proper web app
- The reason there are multiple instances in the settings is for redundancy (if one fails, use the next one) but this work is not done yet, we only use the first one in the list, so you don't have to worry about that, you can just add one and that will be enough.

Let me know if you have any questions.

If you do not mind me asking: was the settings difficult to find on your side? I was surprised you find it easier to do by changing the code instead of the current settings.

**Comment by vadimzharov** [comment]
Hey @iBicha ! Thanks for your quick response!
Sorry, I didn't check settings because I didn't realize they actually exist!
I read Readme, but I thought that URL is only if I need to cast from phone.
Probably you can mention in the readme file that there are settings exist to tweak Playlet and for now they allow to change Invidious URL.
Initially I deployed the app using VSCode/Debug and I saw requests to `https://vid.puffyan.us` so for me it was easier to find this URL in the code and change it.

Again, thank you for this great app and your response!

**Comment by iBicha** [comment]
That's great point, I'll add something to the readme, and I've added a UX task to make it more clear that settings can contain more things (the settings tab in playlet doesn't say anything, which is not great)
