### ISSUE TITLE
[Request] Bookmarks Descend by DATE ADDED

### ISSUE THREAD

**Issue by Neipas09** [iBicha/playlet#260]
It would be awesome if when i go to my bookmarks, it automatically moves the newest videos to the top.
And then descends by Date Added.

**Comment by iBicha** [comment]
That's a good idea - thanks for the suggestion!

**Comment by Neipas09** [comment]
I don't think you quite understood what i'm requesting.
I don't see how #263 has anything to do with what i requested.

If you look at this pic, you will see that at the top of the BOOKMARKS is showing a video from 2 days ago.
![image](https://github.com/iBicha/playlet/assets/58871039/188a8690-80ee-4202-a2f4-a04d3f869968)

And when i go down just 1 spot, there's a video from 3 hours ago
![image](https://github.com/iBicha/playlet/assets/58871039/68df2e50-37d0-4306-bc81-4f5de5660853)

My request is to make it so that the bookmarks section automatically puts the NEWEST video at the top, and then sorts them descending by date added.

**Comment by iBicha** [comment]
Aha - I see what you're asking now. You almost want the concept of "Subscription groups" that can be found in [Piped](https://github.com/TeamPiped/Piped) or [NewPipe](https://github.com/TeamNewPipe/NewPipe).
This is a concept that is not available yet in Playlet and Invidious.

What you have is bookmarked channels, not videos. Channels in Playlet can be bookmarked in two ways. One is just a list of channels in a row. Kind of like this:
![bookmarks](https://github.com/iBicha/playlet/assets/17722782/aa529f84-8d81-4da8-8d6b-c7ea70a3b7bb)

This is done when you select a channel, long press "ok", and select `Add to "Channels" bookmark`.

The second way to bookmark channels is to have the row dedicated to that channel (by choosing the `Add to "CHANNEL_NAME" bookmark`) which is what you are showing me.

When you do that, we create a row, the first item in the row is the channel, and the rest of the items are the latest videos from that channel.

You want to sort these channel bookmarks by the date of their last video published. Unfortunately we can't do that, because not all the bookmark rows are of the same type. Some of them are channels (the first type), some of them are playlists, and some of them are single videos. These types are fundamentally different (and can contain a mix of types) so they can't be sorted the way you're describing.

I've began an exploration in a similar space, which is listing channels you subscribed to sorted by last videos they uploaded (see https://github.com/iv-org/invidious/pull/4211) but as I said, I believe you want Subscription groups if I'm not mistaken.

 If that's the case, I suggest opening a feature request in Invidious to support subscription groups.

I hope this helps.
