### ISSUE TITLE
"Press and hold `Options (*)` to show the queue" doesn't work

### ISSUE THREAD

**Issue by nzpei** [iBicha/playlet#280]
I suspect this is a device-specific bug. 

Steps to reproduce:
Note: It doesn't matter if you are logged in or not
1) Play a video
2) Using the web app, queue up another video to play
3) On the TV screen you will see the toast message indicating the video has been queued, and an instruction to "Press and hold Options (*) to open the queue" 
4) Press and hold the (*) button on the physical Roku remote

On a Roku-enabled smart TV, pressing and holding the (*) toggles Roku's built in screen reader mode on. 
If I subsequently turn off the "Screen reader shortcut" in the Roku settings, pressing and holding no longer does that, but also doesn't trigger the expected behavior. Instead, it will momentarily open and then close the left hand side Roku TV settings sidebar for controlling picture settings, audio settings etc. 

On a Roku Streaming Stick, pressing and holding the (*) remote button toggles an Options sidebar menu 

In both instances, pressing and holding (*) on the Playlet web app causes the same behavior. 

Edit: For completeness, a single press of the (*) button does work correctly for returning to full-screen, from a minimized/PiP video view.

**Comment by iBicha** [comment]
Thanks for creating this issue. The Options (*) should work anytime, EXCEPT when a video is playing fullscreen.
This is a Roku OS limitation, since they want users to be consistently able to pull the menu (which allows they to change picture settings, subtitles, etc)
I could work around it, but I don't think it's a good idea (also the Roku folks would not be too happy about it)

So it's sort of a UX issue here (this is why I didn't tag this as a bug):
1. The notification should not say `Press and hold Options (*) to open the queue` when the video is full screen
2. When in full screen, we should have a button that allows access to the queue
    - This will need happen when the Video player UI customization happen (adding buttons to pause, play next, change quality, etc) then we will make room for a button to open the queue

At the very least the first item needs to be fixed so it is not misleading.

**Comment by nzpei** [comment]
Thanks! Makes sense. 

A quick change to the notification prompt message as an interim fix sounds good.

**Comment by nzpei** [comment]
A small semi-related bug:
- When outside of fullscreen mode, you can inadvertently launch multiple instances of the Queue side panel by pressing and holding (*) multiple times
- This seems to just launch the overlay and Queue UI over the top again and again, multiplying the dark overlay over the rest of the UI as well

**Comment by iBicha** [comment]
Yeah that's more of a shortcut to be honest. At the time of making the queue, I had to decide if I wanted to spend more time to have a view layer that is consistently on top of other things, or reuse the view stack (which is also used for opening channels and playlists)
I did test opening multiple queues, and how the screen gets darker, but I decided it's good enough for now, it can be improved later.
It's a prioritization exercise really
