### ISSUE TITLE
QR link not working on playlet app on Roku

### ISSUE THREAD

**Issue by Colinhendricks1** [iBicha/playlet#293]
Unable to sign in to my account due to qr link not working. Always getting an error message when I try to open the qr code.

**Comment by Colinhendricks1** [comment]
![Screenshot_20240211-231247](https://github.com/iBicha/playlet/assets/159743759/bf0a55e6-bc6d-4359-aa8d-9b8209319955)

**Comment by iBicha** [comment]
A valid local ip address should not be `192.168.1.x:8888` it should contain an actual digit instead of `x`, for example this is what my TV shows
![qr](https://github.com/iBicha/playlet/assets/17722782/27d5f6e9-8203-4887-93f7-84c54fa6d468)

Please double check the url, and make sure both the TV and your phone are on the same Wi-Fi / network

**Comment by Colinhendricks1** [comment]
Thank you for the speedy response. New to all this but I understand what you're saying. I will give it a try tonight and update.

**Comment by Colinhendricks1** [comment]
Not sure what happened before but it's working now! Thank you!
