### ISSUE TITLE
Feature Request: Make OK button act as Play/Pause when watching a video.

### ISSUE THREAD

**Issue by EricLauber** [iBicha/playlet#296]
When watching a video, the official YouTube app, Netflix app, and other apps will respond to pressing the OK button on a remote and pause a video. Pressing it again will restart the video. Pressing OK in playlet while playing a video does not appear to cause any action.

I am not sure if there is other behavior associated with the OK button in those apps, but please at the very least make pressing OK mimic Play/Pause while watching a video.

**Comment by iBicha** [comment]
Thanks for the suggestion.
So on the YouTube app, the first OK press does brings up the progress bar UI, but does not pause the video. The second OK pauses the video. Pressing again would resume.
Additionally, the OK button can have different function based on context (like resuming the video at a different position after scrubbing using the left/right buttons) so handling the OK button requires handling the state of the player and its UI.
Right now, Playlet is using the "Standard" video player from Roku (with some cosmetic changes.). In order to change behaviour such as what the OK button does, we need to re-implement the player UI entirely.
Not to say this won't be done, in fact it is on the roadmap, which is supposed to add various UI controls (play/pause, previous, next, play speed, quality selector, caption language, etc), but until that's done, this change won't happen until the new UI is ready unfortunately (even though it might look like a simple change)

**Comment by EricLauber** [comment]
That makes sense to me! This is pretty low on the priority list as there's a way forward (to hit Play/Pause), it's just a muscle memory thing. Thanks for the quick response.

**Comment by iBicha** [comment]
Big thanks to @cexcell who fixed this with #307
