### ISSUE TITLE
Shorts playback is corrupted

### ISSUE THREAD

**Issue by mxxcon** [iBicha/playlet#298]
I noticed that all shorts don't play correctly.
They play fine for a few seconds but then the whole video turns green or purple or some other compression artifacts and garbage and it continues until the end, if perhaps randomly for a few sec videos clear up and then turn back to garbage.

Using 0.19.2 on Roku Premier+ (4630X)

**Comment by TheBossMan3** [comment]
Works for me. Try restarting your TV or reinstalling Playlet.

**Comment by iBicha** [comment]
Does all shorts have the exact same issue?
What I can suggest is setting the quality to something else (if you have it set to `Auto (DASH)`, try `720p`) and see if it fixes the issue.
I have not seen compression artifact issues on any shorts before (or any videos for that matter) so this is harder for me to investigate. Besides, Roku does not have any kind of low level debugging capabilities that allows me to dig into this further unfortunately.

**Comment by mxxcon** [comment]
I just tried it again and it seems to be happening only on "Auto(dash)" setting. 720p and Medium seem to play fine.
Every time I tried playing the same short the corrupt happens at the same spot.

**Comment by iBicha** [comment]
Thanks for confirming. It terms of what is actually happening, the video being played using DASH is probably of the codecs VP9 or AV01, while the 720p is AVC1. What's happening is that the player is choking on the video because of decoding bugs, but I don't have access to the internals of Roku to see why. There are some APIs that indicate if the device can or can't play a video at all, but that's it.
For now, all we can do is hope that Roku is tracking decoding errors internally and that they are updating their software to fix this in the future.
For you, it can be a compromise to set the quality to `720p` if shorts are important to you. Either way, Playlet can't (yet) differentiate between a video and a short (see #81) so we can't treat shorts separately.
I will close this issue for now because there's no possible resolution currently, but we can reopen if that changes.

**Comment by mxxcon** [comment]
So on TCL tv model 55P607
(I think its Roku model is 7103X) and Roku Streaming Stick 4K 3802X play fine.

But on Streaming Stick 3600X this short has corrupted playback similar to my 4630X. And similarly 720p plays fine.

**Comment by iBicha** [comment]
Thanks for reporting back. I'll keep an eye on this, as I'm still trying to figure out many things related to codecs (quality, making 4k support work etc) I'll keep this in mind
