### ISSUE TITLE
Can you cast from a PC to Playlet via Lounge API?

### ISSUE THREAD

**Issue by TheBossMan3** [iBicha/playlet#299]
Using the Lounge API, I assumed that it would also work on a PC, but when I go to YouTube.com in Google Chrome and I click on cast, it does not work. Just clarifying since there is not a lot of documentation on Lounge API and you said in your release notes that you can cast from chrome.

**Comment by iBicha** [comment]
Yes, Chrome is supposed to work
<img width="399" alt="Screen Shot 2024-02-21 at 12 26 58 PM" src="https://github.com/iBicha/playlet/assets/17722782/03d04e61-e0a7-437f-809b-17ca47a6e917">

But it can be a bit wonky. If you connect, but nothing happens, try refreshing the browser tab and try again.
I believe because once you connect for the first time, the lounge session is not started yet, and perhaps that's why the casting doesn't work yet. Once you refresh and cast again, it should work.
This stuff is hard to debug (took a while for Playlet to show in the list of devices in the first place) so I don't know exactly how to proceed to make it work better (besides sitting down and keep trying things until something works)

Let me know if this helps.

**Comment by TheBossMan3** [comment]
Did you

**Comment by iBicha** [comment]
One more note: if the lounge in Playlet is already "active" (meaning you already connected a phone, or you opened the "Link with TV code" once since you started Playlet) then it should connect as normal, no need to refresh.
