### ISSUE TITLE
[BUG] Unable to use different/new instance URL for custom instance

### ISSUE THREAD

**Issue by awainwright** [iBicha/playlet#322]
Recently I had updated my invidious instance to use a different domain. The instance has the same hostname, but the domain and TLD are different. I also updated the TLS cert to reflect it. It works fine on a browser and even on the Invidious client on my phone. When I try to change the instance URL in Playlet and test, the only pass I get is a valid URL. All other tests failed. I thought this was odd so I did some tests. 
First, I uninstalled and reinstalled Playlet. No luck. So I factory reset the Roku TV. Still no luck. So then I reverted my Invidious instance to the old URL, and all the tests passed just fine. Literally the only difference was the URL and the cert to match. I'm not sure what the issue could be here? But this is really odd. I should also note, that selecting a public Invidious instance works as well, it's just when I use my new URL that it fails for some reason. I should also note this is all on my Intranet, my Invidious instance is not public.

**Comment by awainwright** [comment]
Update: I tested adding the instance with a new Roku account, and same issue. My Invidious instance with the new URL is actually a new instance I stood up from scratch, so it's not the same instance that was using my old URL. Which is still weird, because even in my new instance, it accepts my old URL but not my new one.

**Comment by iBicha** [comment]
Can you share a bit more about the error? 
Maybe under the "Test instance" window, select the "instance reachable" test and see what the error is.
You can also check/share the logs using `http://ROKU_IP:8888/logs/app_logs.txt`

**Comment by awainwright** [comment]
Sure, here is the log. 
As far as the Instance reachable error, it says that is could not resolve host. That is a little strange, since it is able to resolve my old host. Roku's network settings have not changed either. It also doesn't work on any of my other Roku TVs. What else is odd, is that when I open Playlet in my browser, it actually does let me log in and it loads videos, with the exception of the playlists and watch history. I don't think it's my TV since it does load my old URL and the same is happening on all my TVs.
[Playlet_log.txt](https://github.com/iBicha/playlet/files/14548241/Playlet_log.txt)

**Comment by iBicha** [comment]
> Sure, here is the log.
As far as the Instance reachable error, it says that is could not resolve host. That is a little strange, since it is able to resolve my old host. Roku's network settings have not changed either. It also doesn't work on any of my other Roku TVs. What else is odd, is that when I open Playlet in my browser, it actually does let me log in and it loads videos, with the exception of the playlists and watch history. I don't think it's my TV since it does load my old URL and the same is happening on all my TVs.

This boils down to how Roku devices resolve hosts. This kind of similar to my case, where it wouldn't resolve a local `http://my-server.local` (which is setup on a local ubuntu machine) - it can only see it if I set the local ip address.

When I run `nslookup` on any public instance, e.g.
```
nslookup invidious.fdn.fr
```
I get a valid ip address.

But when I run `nslookup` on my local instance
```
nslookup my-server.local
```
I get a `server can't find my-server.local: NXDOMAIN`

So I'm guessing local domains are made known in the network using [mDNS](https://en.wikipedia.org/wiki/Multicast_DNS), that maybe Roku does not implement. This is only my guess, I could be wrong. Let me know if this is the case for you as well, or it is a separate issue.

PS: I deleted your comment (just in case) because I saw the logs contained an Invidious access token. I apologize, I should have warned you about that.

**Comment by awainwright** [comment]
UPDATE: I found a solution. So the setup I had before was that the DNS record for my Invidious instance was in my Active Directory DNS server. That DNS server would then forward to my pi-hole server. For whatever reason, Roku does not like DNS entries from an AD DNS Server I guess. So instead, I made my my pi-hole server the primary DNS server, and it forwards requests to the AD DNS server as needed. Then, the Invidious instance can either be added as a record to the pi-hole server, or the DNS server, and it seems like it works. 
I don't know if this will help anyone else, maybe... But if you use your own internal DNS server(s), and AD is one of them, make sure requests get forwarded to that, and not the other way around.
