### ISSUE TITLE
Thank you!! Donate?

### ISSUE THREAD

**Issue by micahmo** [iBicha/playlet#325]
Hey, I just wanted to say thank you so so much for Playlet. All of my media devices are Rokus and I've hated how terrible YouTube is, how there's no support for SponsorBlock or sideloading, how it progressively gets slower and slower, etc., etc. I checked out Playlet a while ago in its infancy, and it worked ok, but it was very primitive. I just checked it out again, and it's literally a fully-featured replacement for YouTube. I uninstalled YT from my devices and I'm so happy with Playlet. The mobile web UI is also awesome.

This fills such a big hole that I feel it deserves more recognition! I will try to mention this whenever anyone brings up the popular YouTube alternative apps like NewPipe (Android), SmartTubeNext (Android/Google TV), FreeTube (desktop), Yattee (Apple). This deserves to be right there among the best.

Is there any way to monetarily contribute to this project, even just to throw a few bucks your way for the awesome work?

**Comment by iBicha** [comment]
Thank you for the kind words, I appreciate the praise, and it's very encouraging!

I want to keep Playlet free (both [free as in freedom, and free as in beer](https://opensource.stackexchange.com/questions/620/what-is-the-difference-between-free-as-in-beer-and-free-as-in-speech#:~:text=%22Free%22%20is%20ambiguous%20in%20English,opinion%20(you%20are%20free).)) and since I'm fortunate with a day job to support myself, I do not see the need to setup donations.

I'm glad the app is adding value to many people (and I appreciate all the kind words from everyone) as we're currently peaking at 1693 hours streamed per day ad free based on the [stats](https://github.com/iBicha/playlet/wiki). That's a decent amount of useless unwatched ads, and it makes me happy. So please do feel free to spread the word so that more can benefit from it.

**Comment by micahmo** [comment]
Thank you for the response and I'm glad to hear you're well supported. Good luck with everything!
