### ISSUE TITLE
Doesn't always play the requested video

### ISSUE THREAD

**Issue by Patriot2407** [iBicha/playlet#418]
I keep running into an issue where I select a video and the video next to it is the one that plays, or if the video is much older it could be out of order by a few videos and to play the one i want I have to keep trying various videos. I don't have this issue on any of my other invidious clients.
Also, I love this app, and greatly appreciate it! Thanks!

**Comment by iBicha** [comment]
Thanks for reporting, I believe I know what this is about.
When you select a video, the "last focused video" is the one to play. But if you navigate between videos and push the Ok button too quickly, the video you want didn't receive the focus yet, so the one next to it would play.
I find it mildly inconvenient (because I'm fast on the remote and want the app to react quickly) but the workaround is to wait half a second until the focus is on the video you want to play before selecting it.
I worked on a fix a while back, but I didn't like the fix itself so I didn't push it. I'll look into it.

**Comment by Patriot2407** [comment]
Ok thanks, at least I know how to get around this issue

**Comment by iBicha** [comment]
> Ok thanks, at least I know how to get around this issue

Fixed in the Canary release https://github.com/iBicha/playlet/releases/tag/canary
It will be part of the next version

**Comment by Patriot2407** [comment]
Awesome, I look forward to it!
