### ISSUE TITLE
Text shown, videos blank, 

### ISSUE THREAD

**Issue by tlc** [iBicha/playlet#42]
I have invidious running at home (and working).  I just added playlet, 0.6.0 from the store.

I press "Login" in the setup process, I see "Logged In: true" and the screen on the TV refreshes.  On the TV, under Subscriptions (and the other section titles) the text has changed to _my_ subscriptions, but the video squares are blank.

If I try to play a video, I get a dialog with:

> Error playing video
> ...
> dbgmsg: got invalid pathname, load the next one
> category: mediaplayer
> errcode: 8
> drmerrcode: 0

**Comment by iBicha** [comment]
Thanks for reporting @tlc 
Can you share more information?

- Screenshot/photo of the screen showing the issue
- The url of the video failing to play (if it is a specific video)
- Invidious instance you're using (or whether you're hosting your own)
- Paste the content from `http://ROKU_IP_ADDRESS:8888/api/state` (e.g. `http://192.168.1.2:8888/api/state`)

The more details you can share, the better I can track down the origin of the issue.

**Comment by tlc** [comment]
![IMG_1039](https://user-images.githubusercontent.com/19436/213901532-42b55c15-388d-4931-9df9-ab3469ad1d1e.jpeg)
![IMG_1038](https://user-i
[state.json.zip](https://github.com/iBicha/playlet/files/10473800/state.json.zip)
mages.githubusercontent.com/19436/213901536-81b7125b-890b-45da-b9f6-58da74959d3f.jpeg)
All videos fail.

**Comment by tlc** [comment]
[state.json.zip](https://github.com/iBicha/playlet/files/10473802/state.json.zip)
![IMG_1039](https://user-images.githubusercontent.com/19436/213901581-91dfb5c2-169d-47c7-a69c-c1b0d5b5a04c.jpeg)
![IMG_1038](https://user-images.githubusercontent.com/19436/213901583-76eb123e-3438-4120-8ce7-07f8eeab84e1.jpeg)

**Comment by iBicha** [comment]
Thank you! In this case, I suspect this is configuration to be done on the Instance.
Here are the fields that I found needed to be configured properly for things to work:
- `domain`: set it to your domain (in your case `svcs.home`)
  - this is so that the urls returned are absolute (`${domain}/thumbnail.jpeg`) and not relative. 
- `hmac_key`: set this to a random value (see [here](https://docs.invidious.io/installation/#post-install-configuration))
  - this is so the auth token used by Playlet does not randomly expire (and does not expire when you restart your instance)
- `external_port`: I believe you need to set this to `3030` in your case
  - this is so that the urls returned are in the form of (`${domain}:${external_port}/thumbnail.jpeg`) and not relative. 

Setting these correctly made my local instance work fine (related https://github.com/meienberger/runtipi-appstore/issues/173#issuecomment-1374543462)

If you are using the docker compose, you should be able to set these fields [here](https://github.com/iv-org/invidious/blob/4e3884cae749ffcc39b77f2dcb6bc336c255d2e5/docker-compose.yml#L21)

Let me know if this fixes your issue

**Comment by tlc** [comment]
That was it.  Thanks for the help and for playlet!
