### ISSUE TITLE
Can't remove a bookmark of a channel/playlist that have been removed by Youtube

### ISSUE THREAD

**Issue by BrewCoffeeAddict** [iBicha/playlet#421]
Hello,

I added a channel or a playlist to my bookmarks but Playlet can't load it anymore. I suspect the content has been removed by Youtube. I have a message next to it saying (Failed to load). My only option seems to long press ok and select "Refresh Bookmarks" in the menu
Then this brings me a pop up with the following error:

```
Failed to load feed
Reason: Bot Found
StatusCode: 404
Requestid 122683558
Body: {"error":"Could not extract playlistSidebarRenderer"} 

```
It would be great if it was possible to long press ok and select "Remove bookmark" from the menu. Just to make things cleaner.
It's not a big deal everything works fine except getting this error.

Thanks again for making this app and for all your hard work!

**Comment by iBicha** [comment]
Thanks for reporting this issue
I've covered this when it happened with videos (e.g. a video deleted or made private) but I have not considered the case where a playlist/channel becomes unavailable. I'll look into it

**Comment by iBicha** [comment]
I dug into it and I see I need to make fundamental changes to address this properly.
To be pragmatic I just did some minimal changes to fix the issue only for playlists, since they are more common to be deleted or made private (deleting channels is less common, I imagine)
The fix is now in the Canary release https://github.com/iBicha/playlet/releases/tag/canary and will be available in the next version of Playlet
