### ISSUE TITLE
Content advisory http request error

### ISSUE THREAD

**Issue by bingledore** [iBicha/playlet#433]
Whenever trying to play a video that has a content warning popup, it give an http request error and cannot play any videos with the tag.

For example, most police bodycam videos have these warnings, and do not work.

**Comment by iBicha** [comment]
This is known issue with age-restricted videos in Invidious https://github.com/iv-org/invidious/issues/2189

If you open this random police bodycam video https://www.youtube.com/watch?v=bvZCou0y9cI in a private navigation window, it will show this message
>Sign in to confirm your age
>This video may be inappropriate for some users.

That's why the video does not play. Additionally, the video also does not play on Invidious in the browser.
I will close this issue in favor of https://github.com/iv-org/invidious/issues/2189 once it is fixed, this won't be an issue on Playlet anymore.
