### ISSUE TITLE
Roku OS kills Playlet without my consent

### ISSUE THREAD

**Issue by xa4hf8** [iBicha/playlet#487]
I often find that my Roku device is warm and slow to respond after it has been left alone for several hours.  Even worse, the OS always kills the active app, and then I have to search for the video again if I have paused it.  I often wonder if Roku is running a crypto-miner on my device (or stealing our electricity and selling the users aggregate CPU time) because the device generates a lot of internet traffic when it should be sleeping.  Is there any kind of process monitor that I could install on this platform?

**Comment by iBicha** [comment]
PS: also, if the app is being killed for memory usage, then you can check the logs (accessible from the web app).
The logs would show low memory warnings

**Comment by iBicha** [comment]
Another tool that can be used is https://devtools.web.roku.com/profiler/viewer (see https://developer.roku.com/en-ca/docs/developer-program/dev-tools/brightscript-profiler.md)

For what it is worth, execution timeout errors (basically the UI thread doing "too much work") are famous in Roku apps, and also are very difficult to track down, because the stack trace shows no indication of what is actually causing slowdowns (and OS deciding to shutdown the app altogether)

I constantly try to analyze and eliminate any obvious offenders in the code, and I welcome anyone to make a PR with improvements, but this issue risk never being closed, since there will always be a small percentage of crashes (see https://github.com/iBicha/playlet/wiki#channel-health)

Closing, since I would like to keep issues that we can take actions on, otherwise it is just noise (not that this issue is not legitimate, I'm saying it will be open for a long time without much being done about it)

**Comment by xa4hf8** [comment]
( Sorry for the delay in my response:  I needed to rule out thermal throttling, and disassembled the device to ventilate the case and install a heat sink.  I appreciate the links and will use these tools to collect more data. )

> **To confirm, you pause the video and leave the device for a few hours, and then it becomes slow?**

1.  When I leave the device for a few hours, any running application will be forcibly terminated by Roku OS.  I wondered if this issue is device-specific, or if it affects some branch of Roku OS, or is it a platform-wide issue? Do others experience the same problem?

2.  Sometimes when the device is awakened from an idle state by pressing a key on the remote control, there is a very long delay before it responds -- like it is performing some kind of large calculation and it will not stop until the computation cycle is complete.  (Behavior that is characteristic of crypto-miners or system services which sell networked CPU time from idle machines.)

> **Playlet is not capable of making any web requests when the screen saver is on. So perhaps the OS doing things.**

I was not suggesting that Playlet is the culprit... I just wanted to report that I have seen lots of network activity when the Roku device should be sleeping (in power-saving mode), and that is another characteristic of crypto-miners, et cetera.
