### ISSUE TITLE
Playlet 'other language' Support

### ISSUE THREAD

**Issue by Dxbtechie** [iBicha/playlet#488]
Hello team,
Been using this remarkable app for a while now and it's just awesome.
How do one enable language support within? Only English characters are displayed properly...the rest are not well depicted.

How can we correct this?

Thank you

**Comment by iBicha** [comment]
Thanks for reporting. Roku doesn't support all Unicode, so certain characters like asian and arabic scripts are not supported. Roku does this to save disk space on their ships.
To be accurate, not only English is supported. Here's the list https://github.com/iBicha/playlet/blob/92091a66558b004a71ceeea1a7e973d1b14c55c4/playlet-lib/src/config/ISO-639-1-to-ISO-639-2T.json5#L4-L11

I will close this issue because we already have one https://github.com/iBicha/playlet/issues/229
