### ISSUE TITLE
Leaving playlet backend set to 'playlet (local)' with no invidious backend set

### ISSUE THREAD

**Issue by anaxonda** [iBicha/playlet#495]
Hi there, 

I'm a bit confused about the need (or not) of setting an invidious backend. In a short test it seems like most features are working with just the playlet backend? Except `channel load error` when trying to view channels.

I'd like to leave playlet set up for non-technical people, for whom changing invidious backends would be a big ask.

Is the playlet backend likely to keep working fine without intervention?

**Comment by iBicha** [comment]
Thanks, so let me clarify
So the Playlet backend is in the playback settings, and it says `The backend used for fetching video data`. So it is only used for playing videos. The rest is still done through Invidious. This backend was added urgently because most Invidious instances get blocked at the level of streaming the video. But the rest usually still works.

With that in mind, even with the Playlet backend, you still need an Invidious instance.
When the Invidious instance is not set, a default one is selected. Right now it is set to https://invidious.jing.rocks (it used to be https://invidious.fdn.fr). Normally users would set the instance they want, but I also wanted people to be able to start using without doing any settings, thus the default instance stuff.

The problem with the current default instance (https://invidious.jing.rocks) is that it was last updated on 2024.11.01, while there is the bug `channel load error when trying to view channels.` was fixed and merged around 2024.11.10

> I'd like to leave playlet set up for non-technical people, for whom changing invidious backends would be a big ask.

I get it, I'm keeping this in mind, that perhaps I need to implement all the functionality (channels, playlists, trending, and so on) in Playlet independently from Invidious - I don't know yet. But for now I hope this clarifies things a bit.

**Comment by anaxonda** [comment]
> I get it, I'm keeping this in mind, that perhaps I need to implement all the functionality (channels, playlists, trending, and so on) in Playlet independently from Invidious - I don't know yet. But for now I hope this clarifies things a bit.

That does clarify things well, thank you. 

I would say more independent the better! But as is is still pretty good, the basic search/play function is fine.
