### ISSUE TITLE
Feature request - Subscription browser

### ISSUE THREAD

**Issue by rudism** [iBicha/playlet#51]
It'd be nice to have a more subscription-oriented view when authenticated to an invidious instance. For example a "subscriptions" tab that only shows new videos from subscribed channels, and ideally a way to drill down to specific subscriptions and see just that channel's videos.

I'm not sure how typical my use case is, but I have zero interest in ever seeing any of the "trending" categories and use YouTube/Invidious strictly to view content from subscribed channels.

**Comment by iBicha** [comment]
Thanks for the feature request!

That does make a lot of sense, in fact I'm on the same boat (the trending videos are super uninteresting) - they're only there because I thought since they are popular/trending, it means someone people would want these.

The idea with Playlet is to make the view completely customizable: you choose the number of tabs, and what each tab shows. The intention is to have an "editor" for the layout you want (probably through the web app). You could show a predefined list of playlists, or channels, or a list of searches in a tab. This allows people to have a feed that reflects what they are interested in in general, and not necessarily channels they are subscribed to.

Right now the layout system is half-baked, and the home page is [hardcoded here](https://github.com/iBicha/playlet/blob/main/playlet-lib/src/config/default_home_layout.json)

Additionally, we're still missing a channel view, that shows a channel, name, image, and uploaded videos (and uploaded playlists). I think this need to be built first, and then we can add a tab specifically for subscriptions, and finally the fully fleshed out layout customization.

Overall this definitely feels like a feature to fit into v0.8.0 or v0.9.0

**Comment by bryceharrington** [comment]
I'd like to be able to set per-subscription:

  - Whether to show only unwatched (already exists for all feeds, but this should be a per-subscription setting)
  - Number of items to show (for some subscriptions I want no more than N items, others unlimited)
  - Max age of unwatched items (i.e. if latest video was from 3 days ago I don't want to see it)
 
 I'm with you two that the trending/popular feeds aren't well matched to my interests, and I'd much rather just focus on my manually selected subscriptions.  So being able to configure that would be a huge advantage.

**Comment by WizardOfWor1969** [comment]
I second this. You know jut a switch to only show subscriptions would work as a stop gap. I really dislike the content of some of these videos that youtube are promoting.

**Comment by iBicha** [comment]
Just released a new version with "Bookmarks".
Bookmarks allows you to set a page with what interests you, being your subscription list, your list of playlists, or even specific videos, playlists and channels. Even a search can be bookmarked.
Although still an experimental feature, it should be a good start to focus what you care about.
I will try to evolve this concept towards more customization.
