### ISSUE TITLE
Problem with new Roku OS Version

### ISSUE THREAD

**Issue by 3dmax1979** [iBicha/playlet#517]
I Have two Roku StreamBars. One with 14.0.4 Build 12221 and one with 14.1.4 nuild 7709. The newer one has allwaves error 401 if i search for videos. I have Playlet Version 0.25 from Roku Store.

**Comment by iBicha** [comment]
Thanks for reporting, sounds like it could be related to https://github.com/iBicha/playlet/issues/511
Can you confirm
- Playlet lib version (you can see this in the info screen)
- The Invidious instance you're using (find it in the settings)

**Comment by 3dmax1979** [comment]
playlet lib 0.35
Invidious Playlet local

**Comment by 3dmax1979** [comment]
StatusCode 401
Requestld 122683405
Body API disabled

**Comment by iBicha** [comment]
Playlet local instance doesn't return that error
See https://github.com/iBicha/playlet/issues/511#issue-2751866484
The Invidious instance you are using is limiting API access (see more details here https://github.com/iBicha/playlet/issues/519#issuecomment-2560444217)

If you removed the instance url from the settings, but still logged in, you will still use the insurance (because a profile is linked to an instance, it is not portable)
As long as you are logged in with a particular instance, the instance will be used to fetch profile specific things (like subscriptions, playlists and watch history)
I hope this helps.

**Comment by 3dmax1979** [comment]
del the Invidius instance and all works very nice. Bug fix.

**Comment by iBicha** [comment]
Glad it fixed your issue
