### ISSUE TITLE
Remember login

### ISSUE THREAD

**Issue by Patriot2407** [iBicha/playlet#65]
I have to login over again almost every day, but not on my phone, is there anyway to get playlet to retain my authentication so I don't have to login fresh every day?

**Comment by iBicha** [comment]
Which instance are you using?

This is most likely be a configuration issue on Invidious.
It's very important to set the [hmac_key](https://docs.invidious.io/installation/#post-install-configuration), otherwise it will be regenerated on restart, and all existing tokens become invalid. [In fact 3 fields are important to configure](https://github.com/iBicha/playlet/issues/42#issuecomment-1399532626) to have it working properly.

If you own the used instance, then configure it, if you're using a [public instance](https://api.invidious.io/), you might need to reach out to the maintainer and ask them to configure things properly.

**Comment by Patriot2407** [comment]
thank you, yes I self-host and did not set hmac_key, it is now set and restarted, I will report back if this resolved, thanks for your timely response!

**Comment by Patriot2407** [comment]
This resolved my issue thanks!
